// <auto-generated> This file has been auto generated by EF Core Power Tools. </auto-generated>
#nullable disable
using System;
using System.Collections.Generic;
using System.ComponentModel.DataAnnotations;
using System.ComponentModel.DataAnnotations.Schema;

namespace CarShareRestApi.Models
{
    public partial class Account
    {
        //Constructoren til vores Account objekt. Vi bruger HashSet<Car>() til 
      /*  public Account()
        {
            car = new HashSet<Car>();
        }*/

        //Vores primary key, som gør at alle accounts har et unikt Id. Dette er automatiseret i databasen med IDENTITY (1, 1).
        [Key]
        [Column("AccountID")]
        public int AccountId { get; set; }
        
        //
        [Required]
        [StringLength(255)]
        public string UserName { get; set; }
        [Column(TypeName = "date")]
        public DateTime DateOfBirth { get; set; }
        [Required]
        [StringLength(255)]
        public string UserAddress { get; set; }
        public int Phone { get; set; }
        [Required]
        [StringLength(255)]
        public string Email { get; set; }

        [InverseProperty(nameof(Car.Account))]
        public virtual ICollection<Car> car { get; set; }

    }
}