// <auto-generated> This file has been auto generated by EF Core Power Tools. </auto-generated>
#nullable disable
using System;
using System.Collections.Generic;
using System.ComponentModel.DataAnnotations;
using System.ComponentModel.DataAnnotations.Schema;

namespace CarShareRestApi.Models
{
    [Table("CarPooling")]
    public partial class CarPooling
    {
        [Key]
        [Column("CarPoolID")]
        public int CarPoolId { get; set; }
        [Column("AccountID")]
        public int AccountId { get; set; }
        [Required]
        [StringLength(255)]
        public string StartDestination { get; set; }
        [Required]
        [StringLength(255)]
        public string EndDestination { get; set; }
        [Column(TypeName = "date")]
        public DateTime DriveDate { get; set; }
        [Required]
        public byte[] DriveTime { get; set; }
        [Column(TypeName = "decimal(18, 0)")]
        public decimal Price { get; set; }
        public int NumberOfSeats { get; set; }

        [ForeignKey(nameof(AccountId))]
        [InverseProperty("CarPoolings")]
        public virtual Account Account { get; set; }
    }
}