// <auto-generated> This file has been auto generated by EF Core Power Tools. </auto-generated>
#nullable disable
using System;
using Microsoft.EntityFrameworkCore;
using Microsoft.EntityFrameworkCore.Metadata;

namespace CarShareRestApi.Models
{
    public partial class CorolabPraktikDBContext : DbContext
    {
        public static readonly string Connectionstring = "Server=tcp:stressballserver.database.windows.net,1433;Initial Catalog=CorolabPraktikDB;Persist Security Info=False;User ID=EmmaLaila;Password=Corolab1;";
        public CorolabPraktikDBContext()
        {
        }

        public CorolabPraktikDBContext(DbContextOptions<CorolabPraktikDBContext> options)
            : base(options)
        {
        }

        public virtual DbSet<Account> Accounts { get; set; }
        //public virtual DbSet<CarPooling> CarPoolings { get; set; }
        public virtual DbSet<RentalCar> RentalCars { get; set; }

        
    }
}