// <auto-generated> This file has been auto generated by EF Core Power Tools. </auto-generated>
#nullable disable
using System;
using System.Collections.Generic;
using System.ComponentModel.DataAnnotations;
using System.ComponentModel.DataAnnotations.Schema;

namespace CarShareRestApi.Models
{
    public partial class RentalCar
    {
        [Key]
        [Column("RentalCarID")]
        public int RentalCarId { get; set; }
        [Column("AccountID")]
        public int AccountId { get; set; }
        [Column(TypeName = "decimal(18, 0)")]
        public decimal Price { get; set; }
        [Required]
        [StringLength(255)]
        public string Brand { get; set; }
        public int NumberOfSeats { get; set; }
        [Required]
        [StringLength(255)]
        public string FuelType { get; set; }
        [Required]
        [StringLength(255)]
        public string Model { get; set; }

        [ForeignKey(nameof(AccountId))]
        [InverseProperty("RentalCars")]
        public virtual Account Account { get; set; }
    }
}